package it.italiaonline.rnd.specification

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author d7392
 * @date 02-08-2018 07.39
 */
@Slf4j
class Environment {
	/**
	 * This method returns always true.
	 */
	Boolean someEnvironmentMethod() {
		true
	}
}
